# Generated by Django 4.2.1 on 2023-05-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_auto_20180403_2232"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="address",
            field=models.CharField(default=2352522463562562, max_length=60),
            preserve_default=False,
        ),
    ]
