# Generated by Django 4.2.1 on 2023-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_contracts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_name",
            field=models.TextField(),
        ),
    ]
