# Generated by Django 4.2.1 on 2023-06-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_alter_task_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(default=0, upload_to="documents"),
            preserve_default=False,
        ),
    ]
