# Generated by Django 4.2.1 on 2023-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_task_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["project", "task_name", "status", "file"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
